<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Institution;
use App\Models\Faculty;
use App\Models\Department;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Database\QueryException;

class UniveristasFakultasProdiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
   public function __construct()
    {
        $this->arrData =  [
            'institutions'=>[
                [

                    'id'   => 'institution_1',
                    'institution_code' => 'INS_1',
                    'institution_name' => 'UIN Syekh Wasil Kediri',
                    'address' => 'Address',
                    'kota' => 'Kota',
                    'provinsi' => 'Provinsi',
                    'kode_pos' => '12345',
                    'phone' => '1234567890',
                    'email' => 'email@example.com',
                    'website' => 'https://www.example.com',
                    'status' => 'aktif',
                    'faculties'=> [
                        [
                            'id'=>'faculty_1',
                            'institution_code'=>'INS_1',
                            'faculty_code'=>'FEBI',
                            'faculty_name'=>'Fakultas Ekonomi dan Bisnis',
                            'deskripsi'=>'Fakultas Ekonomi dan Bisnis',
                            'head_name'=>'NULL',
                            'email'=>'email@example.com',
                            'telepon'=>'1234567890',
                            'status'=>'aktif',
                            'prodies'=> [
                                [
                                    'id'=>'FEBI_1',
                                    'institution_code'=>'INS_1',
                                    'faculty_code'=>'FEBI',
                                    'department_code'=>'AKIS',
                                    'department_name'=>'Jurusan Akuntansi Syariah',
                                    'jenjang'=>'S1',
                                    'akreditasi'=>'A',
                                    'deskripsi'=>'Prodi',
                                    'head_name'=>'NULL',
                                    'kapasitas_mahasiswa'=>0,
                                    'email'=>'email@example.com',
                                ],
                                [
                                    'id'=>'FEBI_2',
                                    'institution_code'=>'INS_1',
                                    'faculty_code'=>'FEBI',
                                    'department_code'=>'EKIS',
                                    'department_name'=>'Jurusan Ekonomi Syariah',
                                    'jenjang'=>'S1',
                                    'akreditasi'=>'A',
                                    'deskripsi'=>'Prodi',
                                    'head_name'=>'NULL',
                                    'kapasitas_mahasiswa'=>0,
                                    'email'=>'email@example.com',
                                ],
                                [
                                    'id'=>'FEBI_3',
                                    'institution_code'=>'INS_1',
                                    'faculty_code'=>'FEBI',
                                    'department_code'=>'MBIS',
                                    'department_name'=>'Jurusan Manajemen Bisnis Syariah',
                                    'jenjang'=>'S1',
                                    'akreditasi'=>'A',
                                    'deskripsi'=>'Prodi',
                                    'head_name'=>'NULL',
                                    'kapasitas_mahasiswa'=>0,
                                    'email'=>'email@example.com',
                                ],
                                [
                                    'id'=>'FEBI_4',
                                    'institution_code'=>'INS_1',
                                    'faculty_code'=>'FEBI',
                                    'department_code'=>'PBIS',
                                    'department_name'=>'Jurusan Perbankan Syariah',
                                    'jenjang'=>'S1',
                                    'akreditasi'=>'A',
                                    'deskripsi'=>'Prodi',
                                    'head_name'=>'NULL',
                                    'kapasitas_mahasiswa'=>0,
                                    'email'=>'email@example.com',
                                ],



                            ],
                        ],
                        [
                            'id'=>'faculty_2',
                            'institution_code'=>'INS_1',
                            'faculty_code'=>'FASYA',
                            'faculty_name'=>'Fakultas Syariah',
                            'deskripsi'=>'Fakultas Syariah',
                            'head_name'=>'NULL',
                            'email'=>'email@example.com',
                            'telepon'=>'1234567890',
                            'status'=>'aktif',
                            'prodies'=> [
                                [
                                    'id'=>'FASYA_1',
                                    'institution_code'=>'INS_1',
                                    'faculty_code'=>'FASYA',
                                    'department_code'=>'SYAR',
                                    'department_name'=>'Jurusan Syariah',
                                    'jenjang'=>'S1',
                                    'akreditasi'=>'A',
                                    'deskripsi'=>'Prodi',
                                    'head_name'=>'NULL',
                                    'kapasitas_mahasiswa'=>0,
                                    'email'=>'email@example.com',
                                ],
                                [
                                    'id'=>'FASYA_2',
                                    'institution_code'=>'INS_1',
                                    'faculty_code'=>'FASYA',
                                    'department_code'=>'HUSY',
                                    'department_name'=>'Jurusan Hukum Ekonomi Syariah',
                                    'jenjang'=>'S1',
                                    'akreditasi'=>'A',
                                    'deskripsi'=>'Prodi',
                                    'head_name'=>'NULL',
                                    'kapasitas_mahasiswa'=>0,
                                    'email'=>'email@example.com',
                                ],
                                [
                                    'id'=>'FASYA_3',
                                    'institution_code'=>'INS_1',
                                    'faculty_code'=>'FASYA',
                                    'department_code'=>'TATN',
                                    'department_name'=>'Jurusan Hukum Tata Negara',
                                    'jenjang'=>'S1',
                                    'akreditasi'=>'A',
                                    'deskripsi'=>'Prodi',
                                    'head_name'=>'NULL',
                                    'kapasitas_mahasiswa'=>0,
                                    'email'=>'email@example.com',
                                ],
                            ]
                        ],
                        [
                            'id'=>'faculty_3',
                            'institution_code'=>'INS_1',
                            'faculty_code'=>'FATAR',
                            'faculty_name'=>'Fakultas Tarbiyah',
                            'deskripsi'=>'Fakultas Tarbiyah',
                            'head_name'=>'NULL',
                            'email'=>'email@example.com',
                            'telepon'=>'1234567890',
                            'status'=>'aktif',
                            'prodies'=>[
                                [
                                    'id'=>'FATAR_1',
                                    'institution_code'=>'INS_1',
                                    'faculty_code'=>'FATAR',
                                    'department_code'=>'MANP',
                                    'department_name'=>'Jurusan Manajemen Pendidikan Islam',
                                    'jenjang'=>'S1',
                                    'akreditasi'=>'A',
                                    'deskripsi'=>'Prodi',
                                    'head_name'=>'NULL',
                                    'kapasitas_mahasiswa'=>0,
                                    'email'=>'email@example.com',
                                ],
                                [
                                    'id'=>'FATAR_2',
                                    'institution_code'=>'INS_1',
                                    'faculty_code'=>'FATAR',
                                    'department_code'=>'AGIS',
                                    'department_name'=>'Jurusan Pendidikan Agama Islam',
                                    'jenjang'=>'S1',
                                    'akreditasi'=>'A',
                                    'deskripsi'=>'Prodi',
                                    'head_name'=>'NULL',
                                    'kapasitas_mahasiswa'=>0,
                                    'email'=>'email@example.com',
                                ],
                                [
                                    'id'=>'FATAR_3',
                                    'institution_code'=>'INS_1',
                                    'faculty_code'=>'FATAR',
                                    'department_code'=>'BARA',
                                    'department_name'=>'Jurusan Pendidikan Bahasa Arab',
                                    'jenjang'=>'S1',
                                    'akreditasi'=>'A',
                                    'deskripsi'=>'Prodi',
                                    'head_name'=>'NULL',
                                    'kapasitas_mahasiswa'=>0,
                                    'email'=>'email@example.com',
                                ],
                                [
                                    'id'=>'FATAR_4',
                                    'institution_code'=>'INS_1',
                                    'faculty_code'=>'FATAR',
                                    'department_code'=>'GMBI',
                                    'department_name'=>'Jurusan Pendidikan Guru Madrasah Ibtidaiyah',
                                    'jenjang'=>'S1',
                                    'akreditasi'=>'A',
                                    'deskripsi'=>'Prodi',
                                    'head_name'=>'NULL',
                                    'kapasitas_mahasiswa'=>0,
                                    'email'=>'email@example.com',
                                ],
                                [
                                    'id'=>'FATAR_5',
                                    'institution_code'=>'INS_1',
                                    'faculty_code'=>'FATAR',
                                    'department_code'=>'TADRBING',
                                    'department_name'=>'Jurusan Tadris Bahasa Inggris',
                                    'jenjang'=>'S1',
                                    'akreditasi'=>'A',
                                    'deskripsi'=>'Prodi',
                                    'head_name'=>'NULL',
                                    'kapasitas_mahasiswa'=>0,
                                    'email'=>'email@example.com',
                                ],
                                [
                                    'id'=>'FATAR_6',
                                    'institution_code'=>'INS_1',
                                    'faculty_code'=>'FATAR',
                                    'department_code'=>'TADRIPA',
                                    'department_name'=>'Jurusan Tadris IPA',
                                    'jenjang'=>'S1',
                                    'akreditasi'=>'A',
                                    'deskripsi'=>'Prodi',
                                    'head_name'=>'NULL',
                                    'kapasitas_mahasiswa'=>0,
                                    'email'=>'email@example.com',
                                ],
                                [
                                    'id'=>'FATAR_7',
                                    'institution_code'=>'INS_1',
                                    'faculty_code'=>'FATAR',
                                    'department_code'=>'TADRMTK',
                                    'department_name'=>'Jurusan Tadris Matematika',
                                    'jenjang'=>'S1',
                                    'akreditasi'=>'A',
                                    'deskripsi'=>'Prodi',
                                    'head_name'=>'NULL',
                                    'kapasitas_mahasiswa'=>0,
                                    'email'=>'email@example.com',
                                ],
                                [
                                    'id'=>'FATAR_8',
                                    'institution_code'=>'INS_1',
                                    'faculty_code'=>'FATAR',
                                    'department_code'=>'TADRBINA',
                                    'department_name'=>'Jurusan Tadris Bahasa Indonesia',
                                    'jenjang'=>'S1',
                                    'akreditasi'=>'A',
                                    'deskripsi'=>'Prodi',
                                    'head_name'=>'NULL',
                                    'kapasitas_mahasiswa'=>0,
                                    'email'=>'email@example.com',
                                ],
                            ],
                        ],
                        [
                            'id'=>'faculty_4',
                            'institution_code'=>'INS_1',
                            'faculty_code'=>'FUDA',
                            'faculty_name'=>'Fakultas Ushuluddin dan Dakwah',
                            'deskripsi'=>'Fakultas Ushuluddin dan Dakwah',
                            'head_name'=>'NULL',
                            'email'=>'email@example.com',
                            'telepon'=>'1234567890',
                            'status'=>'aktif',
                            'prodies'=>[
                                [
                                    'id'=>'FUDA_1',
                                    'institution_code'=>'INS_1',
                                    'faculty_code'=>'FUDA',
                                    'department_code'=>'I_QURAN',
                                    'department_name'=>'Jurusan Ilmu Al-Qur\'an dan Tafsir',
                                    'jenjang'=>'S1',
                                    'akreditasi'=>'A',
                                    'deskripsi'=>'Prodi',
                                    'head_name'=>'NULL',
                                    'kapasitas_mahasiswa'=>0,
                                    'email'=>'email@example.com',
                                ],
                                [
                                    'id'=>'FUDA_2',
                                    'institution_code'=>'INS_1',
                                    'faculty_code'=>'FUDA',
                                    'department_code'=>'I_HADITS',
                                    'department_name'=>'Jurusan Ilmu Hadits',
                                    'jenjang'=>'S1',
                                    'akreditasi'=>'A',
                                    'deskripsi'=>'Prodi',
                                    'head_name'=>'NULL',
                                    'kapasitas_mahasiswa'=>0,
                                    'email'=>'email@example.com',
                                ],
                                [
                                    'id'=>'FUDA_3',
                                    'institution_code'=>'INS_1',
                                    'faculty_code'=>'FUDA',
                                    'department_code'=>'KPI',
                                    'department_name'=>'Jurusan Komunikasi dan Penyiaran Islam',
                                    'jenjang'=>'S1',
                                    'akreditasi'=>'A',
                                    'deskripsi'=>'Prodi',
                                    'head_name'=>'NULL',
                                    'kapasitas_mahasiswa'=>0,
                                    'email'=>'email@example.com',
                                ],
                                [
                                    'id'=>'FUDA_4',
                                    'institution_code'=>'INS_1',
                                    'faculty_code'=>'FUDA',
                                    'department_code'=>'PSI',
                                    'department_name'=>'Jurusan Psikologi Islam',
                                    'jenjang'=>'S1',
                                    'akreditasi'=>'A',
                                    'deskripsi'=>'Prodi',
                                    'head_name'=>'NULL',
                                    'kapasitas_mahasiswa'=>0,
                                    'email'=>'email@example.com',
                                ],
                                [
                                    'id'=>'FUDA_5',
                                    'institution_code'=>'INS_1',
                                    'faculty_code'=>'FUDA',
                                    'department_code'=>'SOSIA',
                                    'department_name'=>'Jurusan Sosiologi Agama',
                                    'jenjang'=>'S1',
                                    'akreditasi'=>'A',
                                    'deskripsi'=>'Prodi',
                                    'head_name'=>'NULL',
                                    'kapasitas_mahasiswa'=>0,
                                    'email'=>'email@example.com',
                                ],
                                [
                                    'id'=>'FUDA_6',
                                    'institution_code'=>'INS_1',
                                    'faculty_code'=>'FUDA',
                                    'department_code'=>'STU_AA',
                                    'department_name'=>'Jurusan Studi Agama-agama',
                                    'jenjang'=>'S1',
                                    'akreditasi'=>'A',
                                    'deskripsi'=>'Prodi',
                                    'head_name'=>'NULL',
                                    'kapasitas_mahasiswa'=>0,
                                    'email'=>'email@example.com',
                                ],
                                [
                                    'id'=>'FUDA_7',
                                    'institution_code'=>'INS_1',
                                    'faculty_code'=>'FUDA',
                                    'department_code'=>'TAS_PS_TERAPI',
                                    'department_name'=>'Jurusan Tasawuf dan Psikoterapi',
                                    'jenjang'=>'S1',
                                    'akreditasi'=>'A',
                                    'deskripsi'=>'Prodi',
                                    'head_name'=>'NULL',
                                    'kapasitas_mahasiswa'=>0,
                                    'email'=>'email@example.com',
                                ],
                            ]
                        ],
                        [
                            'id'=>'faculty_5',
                            'institution_code'=>'INS_1',
                            'faculty_code'=>'PASCA',
                            'faculty_name'=>'Program Pascasarjana',
                            'deskripsi'=>'Program Pascasarjana',
                            'head_name'=>'NULL',
                            'email'=>'email@example.com',
                            'telepon'=>'1234567890',
                            'status'=>'aktif',
                            'prodies'=>[
                                [
                                    'id'=>'PASCA_1',
                                    'institution_code'=>'INS_1',
                                    'faculty_code'=>'PASCA',
                                    'department_code'=>'STUD_DOKIS',
                                    'department_name'=>'Program Studi Doktor Studi Islam',
                                    'jenjang'=>'S2',
                                    'akreditasi'=>'A',
                                    'deskripsi'=>'Prodi',
                                    'head_name'=>'NULL',
                                    'kapasitas_mahasiswa'=>0,
                                    'email'=>'email@example.com',
                                ],
                                [
                                    'id'=>'PASCA_2',
                                    'institution_code'=>'INS_1',
                                    'faculty_code'=>'PASCA',
                                    'department_code'=>'MAG_STUD_EKSYA',
                                    'department_name'=>'Program Studi Magister Ekonomi Syariah',
                                    'jenjang'=>'S2',
                                    'akreditasi'=>'A',
                                    'deskripsi'=>'Prodi',
                                    'head_name'=>'NULL',
                                    'kapasitas_mahasiswa'=>0,
                                    'email'=>'email@example.com',
                                ],
                                [
                                    'id'=>'PASCA_3',
                                    'institution_code'=>'INS_1',
                                    'faculty_code'=>'PASCA',
                                    'department_code'=>'MAG_STUD_HUKUM_KGA',
                                    'department_name'=>'Program Studi Magister Hukum Keluarga Islam',
                                    'jenjang'=>'S2',
                                    'akreditasi'=>'A',
                                    'deskripsi'=>'Prodi',
                                    'head_name'=>'NULL',
                                    'kapasitas_mahasiswa'=>0,
                                    'email'=>'email@example.com',
                                ],
                                [
                                    'id'=>'PASCA_4',
                                    'institution_code'=>'INS_1',
                                    'faculty_code'=>'PASCA',
                                    'department_code'=>'MAG_STUD_ILM_QLQ',
                                    'department_name'=>'Program Studi Magister Ilmu Al-Quran dan Tafsir',
                                    'jenjang'=>'S2',
                                    'akreditasi'=>'A',
                                    'deskripsi'=>'Prodi',
                                    'head_name'=>'NULL',
                                    'kapasitas_mahasiswa'=>0,
                                    'email'=>'email@example.com',
                                ],
                                [
                                    'id'=>'PASCA_5',
                                    'institution_code'=>'INS_1',
                                    'faculty_code'=>'PASCA',
                                    'department_code'=>'MAG_STUD_MNJD_PDKIS',
                                    'department_name'=>'Program Studi Magister Manajemen Pendidikan Islam',
                                    'jenjang'=>'S2',
                                    'akreditasi'=>'A',
                                    'deskripsi'=>'Prodi',
                                    'head_name'=>'NULL',
                                    'kapasitas_mahasiswa'=>0,
                                    'email'=>'email@example.com',
                                ],
                                [
                                    'id'=>'PASCA_6',
                                    'institution_code'=>'INS_1',
                                    'faculty_code'=>'PASCA',
                                    'department_code'=>'MAG_PEND_AG_IS',
                                    'department_name'=>'Program Studi Magister Pendidikan Agama Islam',
                                    'jenjang'=>'S2',
                                    'akreditasi'=>'A',
                                    'deskripsi'=>'Prodi',
                                    'head_name'=>'NULL',
                                    'kapasitas_mahasiswa'=>0,
                                    'email'=>'email@example.com',
                                ],
                                [
                                    'id'=>'PASCA_7',
                                    'institution_code'=>'INS_1',
                                    'faculty_code'=>'PASCA',
                                    'department_code'=>'MAG_PEND_BARB',
                                    'department_name'=>'Program Studi Magister Pendidikan Bahasa Arab',
                                    'jenjang'=>'S2',
                                    'akreditasi'=>'A',
                                    'deskripsi'=>'Prodi',
                                    'head_name'=>'NULL',
                                    'kapasitas_mahasiswa'=>0,
                                    'email'=>'email@example.com',
                                ],
                                [
                                    'id'=>'PASCA_8',
                                    'institution_code'=>'INS_1',
                                    'faculty_code'=>'PASCA',
                                    'department_code'=>'MAG_PEND_BING',
                                    'department_name'=>'Program Studi Magister Tadris Bahasa Inggris',
                                    'jenjang'=>'S2',
                                    'akreditasi'=>'A',
                                    'deskripsi'=>'Prodi',
                                    'head_name'=>'NULL',
                                    'kapasitas_mahasiswa'=>0,
                                    'email'=>'email@example.com',
                                ],

                            ]
                        ],

                    ]
                ],
            ]
        ];

    }

    public function run()
    {
        ini_set('memory_limit', '1024M');
        DB::beginTransaction();
        try{
            DB::table('institutions')->truncate();
            DB::table('faculties')->truncate();
            DB::table('departments')->truncate();
            foreach ($this->arrData['institutions'] as $key => $value) {
                Institution::create([
                    'id'=>$value['id'],
                    'institution_code'=>$value['institution_code'],
                    'institution_name'=>$value['institution_name'],
                    'address'=>$value['address'],
                    'kota'=>$value['kota'],
                    'provinsi'=>$value['provinsi'],
                    'kode_pos'=>$value['kode_pos'],
                    'phone'=>$value['phone'],
                    'email'=>$value['email'],
                    'website'=>$value['website'],
                    'status'=>$value['status'],
                ]);
                foreach ($value['faculties'] as $key => $value) {
                    Faculty::create([
                        'id'=>$value['id'],
                        'institution_code'=>$value['institution_code'],
                        'faculty_code'=>$value['faculty_code'],
                        'faculty_name'=>$value['faculty_name'],
                        'deskripsi'=>$value['deskripsi'],
                        'head_name'=>$value['head_name'],
                        'email'=>$value['email'],
                        'phone'=>$value['telepon'],
                        'status'=>$value['status'],
                    ]);
                    foreach ($value['prodies'] as $key => $value) {
                        Department::create([
                            'id'=>$value['id'],
                            'institution_code'=>$value['institution_code'],
                            'faculty_code'=>$value['faculty_code'],
                            'department_code'=>$value['department_code'],
                            'department_name'=>$value['department_name'],
                            'jenjang'=>$value['jenjang'],
                            'akreditasi'=>$value['akreditasi'],
                            'deskripsi'=>$value['deskripsi'],
                            'head_name'=>$value['head_name'],
                            'kapasitas_mahasiswa'=>$value['kapasitas_mahasiswa'],
                            'email'=>$value['email'],
                        ]);
                    }
                }

            }
            DB::commit();
        }catch(QueryException $e){
            DB::rollBack();
            Log::error('Query Exception:', [
                'message' => $e->getMessage(),
                'sql' => $e->getSql(),
                'bindings' => $e->getBindings(),
            ]);
            return false;
        }
        //

    }
}
